# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript




trigger: none

pool:
  vmImage: 'ubuntu-latest'
  

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: "Install Angular cli"
  inputs:
    command: "custom"
    customCommand: "install -g @angular/cli"
  
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'MongoDBAngular13'

- task: CmdLine@2
  inputs:
    script: 'npm install karma-junit-reporter --save-dev'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'MongoDBAngular13'
    customCommand: 'run build'
    
- task: CmdLine@2
  displayName: "Run Angular tests"
  inputs:
    script: |
      ng test --browsers=ChromeHeadless --code-coverage --watch=false
    workingDirectory: 'MongoDBAngular13'
  
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'testresults/junit/unit-test-result.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/MongoDBAngular13/'
    mergeTestResults: true
    testRunTitle: 'Angular Tests'
  
- task: CmdLine@2
  inputs:
    script: |
      cd MongoDBAngular13
      mv Dockerfile dist/mongo-dbangular13
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: CmdLine@2
  inputs:
    script: |
      cd MongoDBAngular13/dist/mongo-dbangular13
      # ls -R $(Build.SourcesDirectory)
      # ls -R $(Build.SourcesDirectory)/MongoDBAngular13/dist/
      docker build -t chandu2311/finalpocmongoangular .
      docker login -u chandu2311 -p Nayaknayak23
      docker push chandu2311/finalpocmongoangular

# - task: Docker@2

#   inputs:
#     containerRegistry: 'dockerhub'
#     repository: 'chandu2311/finalpocmongoangular'
#     command: 'push'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/MongoDBAngular13/dist/'
    ArtifactName: 'MyArtifact'
    publishLocation: 'Container'
